version: "3"
services:

  app:
    build:
      context: ./php
      args:
        - TZ=${TZ}
    volumes:
      - ${APP_PATH}:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${APP_PATH}:/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./db/log:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-store: