version: "3"
services:

  app:
    build:
      context: ./php
      args:
        - TZ=${TZ}
    volumes:
      - ${APP_PATH}:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      # テスト時に切り替わらなくなるためコメントアウト
      # - DB_CONNECTION=mysql
      # - DB_HOST=db
      # - DB_DATABASE=laravel_local
      # - DB_USERNAME=root
      # - DB_PASSWORD=root
      - TZ=${TZ}

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${APP_PATH}:/app
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

  ## MySQLは一度作ったら後でバージョン変えないこと。ハマる可能性ありなので注意。

  # MySQL5.7を使う場合
  db:
    build: ./mysql
    ports:
      - 4306:3306
    volumes:
      - db-store:/var/lib/mysql

  # 以下MySQL8.0を使う際(ID/PASS:root※.envで設定)
  # db:
  #   image: mysql:8.0
  #   volumes:
  #     - db-store:/var/lib/mysql
  #     - ./db/log:/var/log/mysql
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   environment:
  #     - MYSQL_DATABASE=laravel_local
  #     - MYSQL_ROOT_PASSWORD=root
  #     - TZ=${TZ}
  #   ports:
  #     - 4306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-store: